<a href="https://colab.research.google.com/github/tikcus1/faz-0/blob/main/Lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Applied Linear Algebra - Lab 1
Introduction to NumPy, color grading, linear transformation, matrix operation and motion tracking.


### Contents:

* [Numpy](#Numpy)
* [Arrays](#Arrays)
* [Array Arithmetic](#Array-Arithmetic)
* [Exercise 1](#Exercise-1)
* [NumPy Standard Data Types](#NumPy-Standard-Data-Types)
* [Using array-generating functions](#Using-array-generating-functions)
* [Exercise 2](#Exercise-2)
* [Exercise 3](#Exercise-3)
* [Array Slicing: Accessing Subarrays](#Array-Slicing:-Accessing-Subarrays)
* [Implementing Gaussian Elimination](#Implementing-Gaussian-Elimination)
* [Exercise 4](#Exercise-4)
* [Exercise 5](#Exercise-5)
* [Exercise 6](#Exercise-6)
* [Exercise 7](#Exercise-7)
* [Exercise 8](#Exercise-8)
* [Exercise 9](#Exercise-9)
* [LU Decomposition](#lu-decomposition)
* [Color Grading](#Color-Grading)
* [Exercise 10](#Exercise-10)
* [Exercise 11](#Exercise-11)
* [Exercise 12](#Exercise-12)
* [Exercise 13](#Exercise-13)
* [Exercise 14](#Exercise-14)
* [Exercise 15](#Exercise-15)
* [Linear Transformation](#linear-transformation)
* [Exercise 16](#Exercise-16)
* [Exercise 17](#Exercise-17)
* [Exercise 18](#Exercise-18)
* [Exercise 19](#Exercise-19)
* [Exercise 20](#Exercise-20)
* [Exercise 21](#Exercise-21)
* [Exercise 22](#Exercise-22)
* [Matrix Operation](#matrix-operation)
* [Motion Tracking](#motion-tracking)
* [Exercise 23](#Exercise-23)
* [Exercise 24](#Exercise-24)
* [Exercise 25](#Exercise-25)
* [Exercise 26](#Exercise-26)
* [Exercise 27](#Exercise-27)
* [Exercise 28](#Exercise-28)


# Numpy

Datasets can be made of collections of images, sounds, videos, documents, numerical measurements, or, really anything. Despite the diversity, it will help us to think of all data fundamentally as arrays of numbers.

| Data type	    | Arrays of Numbers? |
|---------------|-------------|
|Images | Pixel brightness across different channels|
|Videos | Pixels brightness across different channels for each frame |
|Sound | Intensity over time |
|Numbers | No need for transformation |
|Tables | Mapping from strings to numbers |


Therefore, the efficient storage and manipulation of large arrays of numbers is really fundamental to the process of doing data science. Numpy is one of the libraries within the scientific stack that specialize in handling numerical arrays and data tables.

[Numpy](http://www.numpy.org/) is short for _numerical python_, and provides functions that are especially useful when you have to work with large arrays and matrices of numeric data, like matrix multiplications.  

The array object class is the foundation of Numpy, and Numpy arrays are like lists in Python, except that every thing inside an array must be of the same type, like int or float. As a result, arrays provide much more efficient storage and data operations, especially as the arrays grow larger in size. However, in other ways, NumPy arrays are very similar to Python's built-in list type, but with the exception of Vectorization.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import math
import cv2

# to make matplotlib plots interactive in jupyter
%matplotlib inline
# Global floating point precision
precision = 2

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The shape of an array is a tuple of integers giving the size of the array along each dimension. A a one dimensional array (shape `(n,)`) corresponds to a vector.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [4]:
a = np.array([1, 2, 3])  # Create a 1 dimensional array i.e. a vector

print("a is type: ", type(a))
print("The shape of the vector a is: ", a.shape)
print(a[0], a[1], a[2])  # indexing
a[0] = 5  # Change an element of the array
print(a)

a is type:  <class 'numpy.ndarray'>
The shape of the vector a is:  (3,)
1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])   # Create a 2 dimensional array i.e. a matrix
print(b)
print("The shape of the matrix b is: ", b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

[[1 2 3]
 [4 5 6]]
The shape of the matrix b is:  (2, 3)
1 2 4


## Array Arithmetic
Basic mathematical functions operate elementwise on arrays and matrices (which are just 2D arrays), and are available both as operator overloads and as functions in the numpy module:

In [6]:
# Define two matrices
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [7]:
# Elementwise difference:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [8]:
# Elementwise product:
#  * is elementwise multiplication, not matrix multiplication!
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [9]:
# Elementwise square root:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [10]:
# Elementwise division:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


<!-- BEGIN QUESTION -->
# Exercise 1
Given three vectors $v_1$, $v_2$ and $v_3$, calculate $v_4$ where
$$
v_4 = 5(v_2 + v_3) + \frac{10(v_2 - v_1)}{4}
$$
$(v_i \in \mathbf{R}^{5})$

In [11]:
# define the three vectors
v1 = np.array([2, 5, 4, 4, 8])
v2 = np.array([3, 4, 1, 8, 8])
v3 = np.array([6, 3, 7, 5, 1])

# calculate v4
v4 = 5 * (v2 + v3) + 10 * (v2 - v1) / 4
print(v4)

[47.5 32.5 32.5 75.  45. ]


<!-- END QUESTION -->

We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [17]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors.
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

# Matrix multiplication.
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

x = np.matrix(x)
y = np.matrix(y)
x * y

219
219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


matrix([[19, 22],
        [43, 50]])

We can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators +, -, * to use matrix algebra.
Make sure the dimensions of the two matrices are compatible. You can use the `np.transpose()` function or the `T` method of NumPy vectors and matrices.

In [18]:
# Create two row vectors
v = np.matrix(v)
w = np.matrix(w)

# Create two matrices
x = np.matrix(x)
y = np.matrix(y)

# Inner product of vectors.
print(v * w.T)

# Matrix multiplication.
print(x * y)

# Matrix Vector multiplication
print(x * v.T)

[[219]]
[[19 22]
 [43 50]]
[[29]
 [67]]


## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types.

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in numpy that generate arrays of different forms. Some of the more common are:


In [19]:
# We use these when the elements of the
# arrays are originally unknown but their size is known.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3), dtype = np.int_)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.empty( (2,3) )

array([[5.01367972e-310, 0.00000000e+000, 4.22374620e-090],
       [3.37559980e-057, 6.77090829e-310, 5.01447866e-310]])

In [22]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create a 3x3 Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<!-- BEGIN QUESTION -->

# Exercise 2
Given vector $v$, calculate the average of its elements using dot product.

In [29]:
# define vector v
v = np.array([10, 4, 5, -2, -6, 5, 1, 0])

# vector of ones
ones_vector = np.ones((np.size(v)), dtype = np.int_)

# calculating the average using dot product
average = v @ ones_vector;
average / np.size(v)

2.125

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Exercise 3
Matrices can *transform* the vectors that they are multiplied with.
define vector $ u = [ 3, -4 ]^T $ and matrix $ A = \begin{bmatrix}2&-3\\2&-2 \end{bmatrix}$ then calculate and plot the result of
$ Au$ which we'll call $v$. We'll have more to say about these transformations.

When multiplying, make sure that $u$ is a $2\times1$ column vector.

In [33]:
# define the vector. this is a row vector
u = np.transpose(np.matrix(np.array([3, -4])))

# define the 2x2 matrix
A = np.matrix(np.array([[2,-3],[2,-2]]))

# output vector is Av (convert v to column)
v = A * u

u = np.matrix(np.array([3, -4]))


# plotting
plt.plot([0,u[0]],[0,u[1]],label='u')
plt.plot([0,v[0]],[0,v[1]],label='Au')
plt.grid()
plt.axis((0, 20, -10, 20))
plt.legend()
plt.show()

IndexError: index 1 is out of bounds for axis 0 with size 1

<!-- END QUESTION -->

### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [ ]:
M = np.random.randint(100, size=(10, 12))
print("Initial matrix: ")
print(M)

In [ ]:
M[1,:] # se|cond row

In [ ]:
M[:,1] # second column

In [ ]:
# assignment can also work for rows and columns. This is really powerful and fast!
M[1,:] = 0
M

In [ ]:
M[:,2] = -1
M

In [ ]:
M[::2] # step is 2, lower and upper defaults to the beginning and end of the array

In [ ]:
M[:3] # first three rows

In [ ]:
M[3:] # rows from row 3 to the end

In [ ]:
# slice a block from the original array
M[1:4, 1:4]

In [ ]:
# slice with different strides
M[::2, ::2]

<!-- BEGIN QUESTION -->

# Implementing Gaussian Elimination
In this exercise we'll try to implement gaussian elimination.
First we create a couple of functions for elementry row operations.

Each of the elementary row operations is the result of matrix multiplication by an elementary matrix (on the left).

# Exercise 4
## Row Swap
For swapping row $i$ with row $j$ in a $m\times n$ matrix $A$, we multiply $A$ by an $m\times m$ matrix $E$ where $E$ is equal to the identity matrix $I_m$ except $E_{ii}=E_{jj}=0,$ and $E_{ij}=E_{ji}=1$. (Equivalently, we can interchange $i$-th row and $j$-th row of the identity matrix $I$ to get $E$.)
For example, if $A$ is a $3\times 3$ matrix and we would like to swap row $1$ with row $3$, then $E$ would be equal to:
  
  $$
   \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0\\ 1 & 0 & 0 \end{bmatrix}
  $$
  
 Now try to define the `row_swap` function which take a matrix $A$ and two indices $i$ and $j$ as its inputs and returns a matrix which is equal to $A$ with its $i$-th row and $j$-th row swapped.

In [ ]:
def row_swap(A, i, j):
    "Swap row i and j in matrix A."
    m = ...
    E = np.eye(m)

    # Fill out certain entries of E with proper numbers
    # For example:
    # E[i, i] = ?
    ...

    return np.around(E @ A, precision)

In [ ]:
A = np.array([[-1,2,3],[4,-5,6],[7,-8,9]])
print("Before row exchange:")
print(A)
print("After row exchange:")
print(row_swap(A, 1, 2))

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Exercise 5
## Row Sum
 For summing $k \times$ row $i$ with row $j$ in a $m\times n$ matrix $A$, we multiply $A$ by the matrix $E$ where $E$  is equal to the identity matrix $I_m$ except $E_{ji}=k$. For example, if $A$ is 3 by 5 and we want to add -2 times $3$ to row $1$. then $E$ would be equal to:
  
   $$
   \begin{bmatrix} 1 & 0 & -2 \\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}
  $$

Now try to define the `row_sum` function which takes matrix $A$, scalar $k$ and indices $i, j$ as its inputs and returns the matrix resulting from adding $k$ times row $i$  to row $j$  in the matrix $A$.

In [ ]:
# A simple exception for when the indices given to row_sum function are equal
class GERowSwapSameIndexException(Exception):
    def __init__(self):
        super().__init__("Error: indices given to the function must be different.")

def row_sum(A,k,i,j):
    "Add k times row i to row j in matrix A."
    if (i == j):
        raise GERowSwapSameIndexException

    m = ...
    E = ...
    # Fill out certain entries of E with proper numbers
    # For example:
    # E[i, i] = ?
    #E[j, :] += k * E[i, :]
    ...

    return np.around(E @ A, precision)

In [ ]:
A = np.array([[1,2,3],[4,-5,6],[7,-8,9]])
print("Before row sum:")
print(A)
print("After row sum:")
print(row_sum(A, 2, 1, 2))

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

# Exercise 6

## Row Scale
For summing $k \times$ row $i$ with row $j$ in a $m\times n$ matrix $A$, we multiply $A$ by the matrix $E$ where $E$  is equal to the identity matrix $I_m$ except $E_{ii}=k$. For example, if $A$ is 4 by 3 and we want to multiply row 3 by -4 then $E$ would be equal to:
  
   $$
   \begin{bmatrix} 1 & 0 & 0 & 0\\ 0 & 1 & 0 &0\\ 0 & 0 & -4 &0 \\
       0&  0 &0 &1 \end{bmatrix}
  $$
The implementation of a function that scales a row of a matrix must be trivial by now. It take a matrix $A$, a scalar $k$ and an index $i$ and returns the matrix that results from  $k$ times row $i$ in the matrix $A$.

In [ ]:
def row_scale(A,k,i):
    "Multiply row i by k in matrix A"
    m = ...
    E = ...
    # Fill out certain entries of E with proper numbers
    # For example:
    # E[i, i] = ?
    ...

    return np.around(E @ A, precision)

In [ ]:
A = np.array([[1,2,3],[4,-5,6],[7,-8,9]])
print("Before row scale:")
print(A)
print("After row scale:")
print(row_scale(A, -3, 1))

# Exercise 7

## Gaussian Elimination
Having defined the elementary row operations, now let's implement gaussian elimination.

Define the function `eliminate` which takes a matrix $A$ and a vector $b$ and applies gaussian elimination on them and then returns the resulting matrix and vector.

In [ ]:
# A simple exception for when the indices given to row_sum function are equal
class GEEliminationErr(Exception):
    def __init__(self, msg):
        super().__init__(msg)

def is_zero(x, epsilon=1e-10):
    return abs(x) < epsilon

def gaussian_elimination(A):
    number_rows = A.shape[0]
    try:
        for i in range(number_rows):
            pivot = ...

            if is_zero(pivot):
                swap_index = (np.where(A[i+1:,i] != 0)[0][0]) + i + 1
                A = ...

            # Eliminate elements below the pivot
            loopRange = ...
            for j in range(loopRange):
                multiplier = ...
                A = ...
                # print("Row operation: ")
                # print(A)

        if A[number_rows-1, number_rows-1] == 0:
            raise GEEliminationErr("Matrix is not full rank. There are no unique solution.")

    except IndexError as exc:
        raise GEEliminationErr("Pivot not found. There are no unique solutions.") from exc
    return A

In [ ]:
# ADD A TEST
test = np.array([[3, 2, 1], [5, 8, 3], [1, 1, 5]])
gaussian_elimination(test)

# Exercise 8

Next, implement the `back_substitution` function. This function solves a linear system of equations that has been transformed into reduced row-echelon form. It takes a matrix $A$ and a vector $b$ in their rref forms and returns the solution of $Ax=b$.

In [ ]:
def back_substitution(A,b):
    n = A.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(n-1, i, -1):
            ...
        ...
    return np.around(np.matrix(x), precision)

# Exercise 9

## Inverse Matrix

Next, implement the `inverse_matrix` function. It takes a matrix $A$  and returns $A^{-1}$.

In [ ]:
def inverse_matrix(A):
    # define an identity matrix
    b = ...

    Aug = ...

    # Applying the elimination
    ref_Aug = gaussian_elimination(Aug)
    ref_A = ref_Aug[:, :-A.shape[0]].copy()
    z = np.zeros(b.shape)
    for col in range(1, b.shape[0] + 1):
        ref_b = ref_Aug[:, -col].copy()
        z[-col] = back_substitution(ref_A, ref_b)

    return z.T

In [ ]:
# define an example matrix
A = np.matrix([[1,1,-1], [1,0,1], [2,1,1]], dtype = float)
print("Original Matrix")
print(A)

print("Inverse of Matrix:")
print(inverse_matrix(A))

# LU Decomposition

We will make use of the `Doolittle's LUP` decomposition with partial pivoting to decompose our matrix $A$ into $PA=LU$, where $L$ is a lower triangular matrix, $U$ is an upper triangular matrix and $P$ is a permutation matrix. $P$ is needed to resolve certain singularity issues. The algorithm is provided as follows.

To calculate the upper triangular section we use the following formula for elements of $U$:
$$
u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}
$$

The formula for elements of the lower triangular matrix $L$ is similar, except that we need to divide each term by the corresponding diagonal element of $U$. To ensure that the algorithm is numerically stable when $u_{jj} << 0$, a pivoting matrix $P$ is used to re-order $A$ so that the largest element of each column of $A$ gets shifted to the diagonal of $A$. The formula for elements of $L$ follows:
$$
l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik})
$$

In [ ]:
def P_matrix(A):
    P = np.zeros(A.shape, dtype=float)

    for row in range(A.shape[0]):
        index = ...
        P[row][index] = 1

    return P

In [ ]:
def lu_decomposition(A):
    L = np.zeros(A.shape, dtype=float)
    U = np.zeros(A.shape, dtype=float)

    P = P_matrix(A)
    PA = P @ A

    ...

    return (P, L, U)

One application of LU decomposition in computing is in the computation of a determinant. The determinant is often computed by taking the product of the elements on the diagonal of both the L and U matrices. Since LU decomposition is quite efficient, this is a computationally efficient way of computing the determinant.

$$A=LU \Rightarrow det(A) = det(L).det(U)$$

* For a triangular matrix, the determinant is just the product of its diagonal elements. So we just need 2n−1 multiplications to get the result.

In [ ]:
A = np.array(
 [[ 1.6, -0.6, -2.,   1.,  -0. ],
 [-1.1, -1.5,  0.2,  1.,   2.7],
 [-0.1, -0.1, -0.,   0.9, -0. ],
 [ 1.1,  1.9,  0.2,  1.7, -0.5],
 [-0.4,  0.2,  0.9, -0.7,  0.3]]
)

P, L, U = lu_decomposition(A)
print("P:")
print(P)
print("A:")
print(A)
print("L:")
print(L)
print("U:")
print(U)

det_L = ...
det_U = ...
print("det A:")
print(det_L * det_U)

<!-- END QUESTION -->

## Color Grading
A digital image is a numerical representation of an image via a set of picture elements known as pixels. A digital image is an array, or a matrix, of square pixels (picture elements) arranged in
columns and rows.
### Grayscale Images
In a (8-bit) greyscale image each picture element has an assigned intensity that
ranges from 0 to 255. A grey scale image is what people normally call a black and
white image, but the name emphasizes that such an image will also include many
shades of grey.

![image.png](attachment:3d32a1e3-9929-4a0f-a286-81bda0b4d334.png)

### RGB Images
The RGB colour model relates very closely to the way we perceive colour with the r,
g and b receptors in our retinas. RGB uses additive colour mixing and is the basic
colour model used in television or any other medium that projects colour with light.
It is the basic colour model used in computers and for web graphics.
The RGB color model is a method of describing colors. In this model each color is represented as a mixture of three basic colors: red, green, and blue. By varying intensities of these components a variety of colors can be obtained.

![image.png](attachment:133324aa-9bbc-494c-a990-926956fd3483.png)


In [ ]:
# import image
dog = plt.imread("images\dog.jpg")
plt.figure(figsize=(10,10))
plt.imshow(dog)
plt.show()

In [ ]:
# Checkout the contents of the dog array
dog.shape, dog

The `color_grader` function works as follows. It takes as its arguments a 3x3 matrix $A$ and an array representing an image. For each image pixel it takes the vector

$$\mathbf{v} = \begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}$$

with RGB coordinates of the pixel, and replaces it with the vector $A\mathbf{v}$, which specifies the new pixel color. Then it displays the image with colors given by the vectors $A\mathbf{v}$. Since valid RGB values are integers between 0 and 255, coordinates of each vector  𝐴𝐯  are rounded to the nearest integer in this range. In particular, if  𝐴𝐯  has negative coordinates they are rounded up to 0, and if it has coordinates exceeding 255 they are rounded down to 255.

Here is the implementation of the `color_grader` function:

In [ ]:
def color_grader(A, img, width=8, height=8):
    A = np.array(A).astype(float)

    if img.dtype == 'uint8':
        img = img.astype(float)/255
    new_img = np.transpose(np.dot(A, np.transpose(img, axes = (0, 2, 1))), axes = (1, 2, 0))
    new_img[new_img < 0] = 0
    new_img[new_img > 1] = 1
    new_img = (255*new_img).astype('uint8')
    plt.figure(figsize=(width,height))
    plt.imshow(new_img)
    plt.show()

In [ ]:
A = np.array([[1 , 0, 0.1], [1, 1.5, 0.1], [0.1, 0.3, 1]])
print(A)
color_grader(A, dog)

In each of the cases below find a $3\times 3$ matrix $A$ which transforms colors of image pixels as indicated. Use the function `color_grader` to display the resulting image of the balloon.

<!-- BEGIN QUESTION -->

## Exercise 10

The matrix leaves the blue component unchanged and sets the other components to 0:

$$B\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} 0 \\ 0 \\ b \\ \end{bmatrix} $$

In [ ]:
R = ...
G = ...
B = ...
print("Matrix Red:")
print(R)
print("Matrix Green:")
print(G)
print("Matrix Blue:")
print(B)
color_grader(R, dog)
color_grader(G, dog)
color_grader(B, dog)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Exercise 11

The matrix interchanges the blue component with the green component:

$$A\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} r \\ b \\ g \\ \end{bmatrix} $$

In [ ]:
A = ...
color_grader(A, dog)

<!-- BEGIN QUESTION -->

## Exercise 12

The matrix deletes blue in the image and keeps the values of red and green:

$$A\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} r \\ g \\ 0 \\ \end{bmatrix} $$

In [ ]:
A = ...
color_grader(A, dog)

<!-- END QUESTION -->

There are a number of algorithms to convert colored images to grayscale images. In colored images each color pixel is described by a triple (R, G, B) of intensities for red, green, and blue, Here are two ways we map that to a single number giving a grayscale value.

- The average method simply averages the values: (R + G + B) / 3.
- The luminosity method is a more sophisticated version of the average method. It also averages the values, but it forms a weighted average to account for human perception. We’re more sensitive to green than other colors, so green is weighted most heavily. The formula for luminosity is 0.21 R + 0.72 G + 0.07 B.

<!-- BEGIN QUESTION -->

## Exercise 13


The matrix replaces all components by their average:

$$A\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} \dfrac{r+g+b}{3} \\[1mm] \dfrac{r+g+b}{3} \\[1mm] \dfrac{r+g+b}{3} \\ \end{bmatrix} $$

In [ ]:
A = ...
color_grader(A, dog)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Exercise 14


The matrix replaces all components by their weighted average:

$$A\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} 0.21 . r + 0.72 . g + 0.07 . b \\[1mm]0.21 . r + 0.72 . g + 0.07 . b \\[1mm] 0.21 . r + 0.72 . g + 0.07 . b \\ \end{bmatrix} $$

In [ ]:
A = ...
color_grader(A, dog)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Exercise 15


The matrix produce a sepia conversion of the image:

$$A\begin{bmatrix} r \\ g \\ b \\ \end{bmatrix}  = \begin{bmatrix} 0.393 . r + 0.769 . g + 0.189 . b \\[1mm]0.349 . r + 0.686 . g + 0.168 . b \\[1mm] 0.272 . r + 0.534 . g + 0.131 . b \\ \end{bmatrix} $$

In [ ]:
A = ...
color_grader(A, dog)

## Linear Transformation

A linear transformation of the plane $\mathbb{R}^2$ is a geometric transformation of the form

$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

Applying a geometric transformation to a given matrix in Numpy requires applying the inverse of the transformation to the coordinates of the matrix, create a new matrix of indices from the coordinates and map the matrix to the new indices.

Let's start with a simple example involving a matrix that represents the indices itself.

In [ ]:
M, N = 3, 4
matrix = np.arange(M*N).reshape((M, N))
matrix

Then, we need to obtain the indices pairs of the matrix in a matrix form. The new indices of the matrix will result from the product of the inverse of the transformation matrix and this matrix, therefore the indices pairs in this case need to be a 2x12 matrix as

$$
P=\begin{bmatrix} 0 & 0 & 0 & 1 & 1 & 1 & 2 & 2 & 2 & 3 & 3 & 3 \\
0 & 1 & 2 & 0 & 1 & 2 & 0 & 1 & 2 & 0 & 1 & 2 \\ \end{bmatrix}
$$

In [ ]:
points = np.mgrid[0:N, 0:M].reshape((2, M*N))
points

An alternative way to get the indices pairs are:

In [ ]:
x, y = np.mgrid[0:N, 0:M]
points = np.vstack([x.ravel(), y.ravel()])
points

Now, apply the transformation to the indices pairs. The new indices pairs need to be integers to map the given matrix to the indices.

As an example, the transformation matrix will be

$$
A=\begin{bmatrix} 2 & 0 \\ 0 & 1 \end{bmatrix}
$$

which corresponds with scaling the plane in the $x$-axis by a factor of 2. Hence, the new indices pairs are

$$
P'=\lfloor A^{-1}P \rfloor=\begin{bmatrix} 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 1 & 2 & 0 & 1 & 2 & 0 & 1 & 2 & 0 & 1 & 2 \\ \end{bmatrix}
$$

In [ ]:
A = np.array(
    [[2, 0],
     [0, 1]]
)
new_points = np.linalg.inv(A).dot(points).astype(int)
new_points

To finish this example, convert the indices pairs to a matrix of indices which in this example corresponds with the resulting matrix.

The $x$ and $y$ components are
$$
x=\begin{bmatrix} 0 & 0 & 1 & 1 \\ 0 & 0 & 1 & 1 \\ 0 & 0 & 1 & 1 \end{bmatrix}, \quad
y=\begin{bmatrix} 0 & 0 & 0 & 0 \\ 1 & 1 & 1 & 1 \\ 2 & 2 & 2 & 2 \end{bmatrix}
$$
and the resulting matrix from the $x$ and $y$ components is
$$
x+Ny=\begin{bmatrix} 0 & 0 & 1 & 1 \\ 4 & 4 & 5 & 5 \\ 8 & 8 & 9 & 9 \end{bmatrix}
$$

In [ ]:
x, y = new_points.reshape((2, M, N), order='F')
x + N * y

### Visual Matrix Transformation

In the following example we will use a bigger matrix, represented as an image for visual support. Once we calculate the new indices matrix we will map the original matrix to the new indices, wrapping the out-of-bounds indices to obtain a continuous plane.

In [ ]:
aux = np.ones((100, 100), dtype=int)
src = np.vstack([np.c_[1*aux, 2*aux], np.c_[3*aux, 4*aux]])
plt.imshow(src)
plt.show()

The linear transformation function might be written as follows:

In [ ]:
def linear_transformation(src, A):
    M, N = src.shape
    points = np.mgrid[0:N, 0:M].reshape((2, M*N))
    new_points = np.linalg.inv(A).dot(points).round().astype(int)
    x, y = new_points.reshape((2, M, N), order='F')
    indices = x + N*y
    return np.take(src, indices, mode='wrap')

## Exercise 16

Scaling the plane in the $x$-axis by a factor of 1.5:
$$
f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} 1.5 & 0 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}
$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 17

Dilating the plane by a factor of 1.8:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} 1.8 & 0 \\ 0 & 1.8 \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 18

Dilating the plane by a factor of 0.5:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} 0.5 & 0 \\ 0 & 0.5 \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 19

Scaling the plane in the $y$-axis by a factor of 0.5:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 0.5 \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 20

Shearing about the $y$-axis with a vertical displacement of $\frac{x}{2}$:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} 1 & 0 \\ \frac{1}{2} & 0 \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 21

Rotation through $45^∘$ about the origin:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} cos\frac{\pi}{4} & -sin\frac{\pi}{4} \\ sin\frac{\pi}{4} & cos\frac{\pi}{4} \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Exercise 22

Reflection in a line with inclination of $45^∘$ through the origin:
$$f\begin{pmatrix} x \\ y \\ \end{pmatrix} = \begin{bmatrix} cos\frac{\pi}{2} & sin\frac{\pi}{2} \\ sin\frac{\pi}{2} & -cos\frac{\pi}{2} \end{bmatrix} \begin{bmatrix} x \\ y \\ \end{bmatrix}$$

In [ ]:
A = ...
dst = linear_transformation(src, A)
plt.imshow(dst)
plt.show()

## Matrix Operation

Videos are made up of frames, which are essentially images. Matrices can represent the color channels of each pixel in a frame. By applying different operations on these matrices we can manipulate videos.

In [ ]:
# Initialize a video capture object for the video file 'walking.mp4'
cap = cv2.VideoCapture('videos/walking.mp4')

# Loop through each frame in the video
while True:
    # Read the next frame from the video
    ret, current_frame = cap.read()
    # Check if the frame was successfully read
    if not ret:
        break # Exit the loop if the video has ended

    cv2.imshow('frame', current_frame)

    # If the pressed key is 'q', break the loop
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

# Release the video capture object
cap.release()

# Close all open windows created by cv2.imshow()
cv2.destroyAllWindows()

## Motion tracking

Motion tracking involves following the movement of a specific object or region of interest in a video. By using matrix operations on video frames we can achieve some simple steps in motion tracking.

This method identifies moving objects by analyzing the difference between consecutive frames.

## Exercise 23

Calculate frame difference of each frame from the first frame.

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...

    cv2.imshow('Frame Difference', difference_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

## Exercise 24

Calculate the absolute difference of each frame from the first frame.

(Absolute difference is generally preferred for its effectiveness in highlighting any change.)

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...

    cv2.imshow('Frame Difference', difference_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

## Exercise 25

Calculate the difference of each frame from its previous frame

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...

    cv2.imshow('Frame Difference', difference_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

## Exercise 26

Change only the direction of movement horizontally.

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...
    new_background_frame = ...

    cv2.imshow('Frame Difference', new_background_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

## Exercise 27

Darken the background of the video by 0.25.

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...
    new_background_frame = ...

    cv2.imshow('Frame Difference', new_background_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

## Exercise 28

Change the bacground of the video by adding frames of exercise 24 to a new image.

In [ ]:
cap = cv2.VideoCapture('videos/walking.mp4')

while True:
    ret, current_frame = cap.read()
    if not ret:
        break

    difference_frame = ...
    new_background_frame = ...

    cv2.imshow('Frame Difference', new_background_frame)

    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()